# Generated by Django 5.1.6 on 2025-02-26 13:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_profit', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('monthly_budget', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('salary_elena', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('salary_maria', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
            ],
            options={
                'permissions': [('can_view_turnover', 'Can view turnover'), ('can_edit_turnover', 'Can edit turnover')],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_profit', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('school_budget', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('budget_elena', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('budget_maria', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
            ],
            options={
                'permissions': [('can_view_turnover', 'Can view turnover'), ('can_edit_turnover', 'Can edit turnover')],
            },
        ),
        migrations.CreateModel(
            name='StudentCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('money_spent', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('remaining_hours', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('remaining_money', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
            ],
            options={
                'permissions': [('can_view_turnover', 'Can view turnover'), ('can_edit_turnover', 'Can edit turnover')],
            },
        ),
        migrations.CreateModel(
            name='TeacherCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('hours_spent', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('salary_teacher', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('budget_teacher', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
            ],
            options={
                'permissions': [('can_view_turnover', 'Can view turnover'), ('can_edit_turnover', 'Can edit turnover')],
            },
        ),
        migrations.CreateModel(
            name='Turnover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('previous_hours', models.DecimalField(decimal_places=1, max_digits=10)),
                ('previous_balance', models.DecimalField(decimal_places=1, max_digits=10)),
                ('current_hours', models.DecimalField(decimal_places=1, max_digits=10)),
                ('current_payment', models.DecimalField(decimal_places=1, max_digits=10)),
                ('total_hours', models.DecimalField(decimal_places=1, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
            options={
                'permissions': [('can_view_turnover', 'Can view turnover'), ('can_edit_turnover', 'Can edit turnover')],
            },
        ),
    ]
