# Generated by Django 5.1.6 on 2025-02-26 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turnover', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnover',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.AddField(
            model_name='turnover',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AddField(
            model_name='teachercalculation',
            name='turnover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnover.turnover'),
        ),
        migrations.AddField(
            model_name='studentcalculation',
            name='turnover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnover.turnover'),
        ),
        migrations.AddField(
            model_name='school',
            name='turnover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnover.turnover'),
        ),
        migrations.AddField(
            model_name='salary',
            name='turnover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnover.turnover'),
        ),
    ]
