# Generated by Django 5.1.6 on 2025-02-27 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnover', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='salary_elena',
            new_name='salary_admin',
        ),
        migrations.RenameField(
            model_name='salary',
            old_name='salary_maria',
            new_name='salary_owner',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='budget_elena',
            new_name='budget_admin',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='budget_maria',
            new_name='budget_owner',
        ),
    ]
