# Generated by Django 5.1.6 on 2025-02-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnover', '0004_alter_turnover_current_payment_alter_turnover_profit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnover',
            name='current_hours',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='turnover',
            name='current_payment',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='turnover',
            name='previous_balance',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='turnover',
            name='previous_hours',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='turnover',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='turnover',
            name='total_hours',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10),
        ),
    ]
